# Workflow name
name: Deploy Storybook Preview

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency: preview-${{ github.ref }}

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-22.04
    outputs:
      output: ${{ steps.deploy-preview.outputs.deploy-url }}
    # Job steps
    steps:
      - uses: actions/checkout@v4

      - name: Read .nvmrc
        run: |
          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: |
          npm run build-storybook --quiet

      - name: Install Netlify
        run: npm install netlify-cli --save-dev

      - name: Deploy preview to Netlify
        id: deploy-preview
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: 'storybook-static'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy Storybook Preview'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

  test:
    runs-on: ubuntu-22.04
    needs: deploy
    steps:
      - name: ${{ needs.deploy.outputs.output }}
        run: |
          ls
