# Workflow name
name: Deploy Storybook Preview

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  # contents: read
  # pages: write
  # id-token: write
  # pull-requests: write
  actions: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  metadata: read
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

concurrency: preview-${{ github.ref }}

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-22.04
    # Job steps
    steps:
      - uses: actions/checkout@v4

      - name: Read .nvmrc
        run: |
          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      # - name: Build and deploy Storybook to GitHub Pages
      #   uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
      #   with:
      #     path: storybook-static
      #     checkout: false # default: true

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: |
          npm run build-storybook --quiet
          ls

      # - name: Upload
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: storybook-static

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source-dir: storybook-static
