# Workflow name
name: Deploy Storybook Preview

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency: preview-${{ github.ref }}

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-22.04
    # Job steps
    steps:
      - uses: actions/checkout@v4

      - name: Read .nvmrc
        run: |
          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: |
          npm run build-storybook --quiet
          ls

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source-dir: storybook-static
          unbrella-dir: storybook-preview
          preview-branch: main
